version: '3'
services:
  webserver:
    container_name: webserver
    image: mariovpirani/laravel 
    volumes:
      - .:/app
    links:
      - db
    ports:
      - "9080:80"
   
    networks:
      - rede
  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8082:80'
    environment:  
      - PMA_ARBITRARY=1
    networks:
      - rede
  db:
    image: mysql:5.7
    restart: always
    volumes:
     - ./data/db:/var/lib/mysql
    ports:
      - "3906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: westwing
      MYSQL_DATABASE: westwing
      MYSQL_USER: westwing
      MYSQL_PASSWORD: westwing
    networks:
      - rede
networks:
  rede:
    ipam:
      driver: default